### ISSUE TITLE
Not compatible with your version of node/npm: asset@0.3.2

### ISSUE THREAD

**Issue by matylla** [tj/asset#23]
$ npm install asset
npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: asset@0.3.2
npm ERR! Required: {"node":"0.4.x"}
npm ERR! Actual:   {"npm":"1.0.6","node":"v0.5.0-pre"}

**Comment by tj** [comment]
yeah there's no guarantee things will work with 0.5.x, and I got burnt with loose requirements on some old libs so I lock everything to 0.4.x now, though this would be fine `>= 0.4.0 < 0.6.0`
