### ISSUE TITLE
asset none

### ISSUE THREAD

**Issue by torgeir** [tj/asset#26]
local file ./assets.json

```
{
    "g.raphael": "0.4.1"
  , "jquery": "1.5.2"
  , "modernizr": "1.7"
}
```

and issuing

```
$ asset
    asset <name ...> required
```

does not install any assets

**Comment by tj** [comment]
forgot to release :D haha, 0.4.0 has it

**Comment by torgeir** [comment]
Hehe, good one, I kept reading the docs, trying all kinds of formats for the assets.json, but couldn't make it work :p
